// 용인 출장마사지 사이트 페이지 데이터
// 모든 description 은 80자 이내(구글/네이버 가이드라인)로 유지합니다.

const districts = [
  {
    slug: '/yongin/cheoin-gu-chuljangmassage/',
    name: '처인구',
    key: 'cheoin',
    title: '처인구 출장마사지｜용인시청·김량장·에버랜드 생활권 안내',
    desc: '처인구 출장마사지·홈타이 예약 전 용인시청, 김량장 생활권을 확인하세요.',
    h1: '처인구 출장마사지 · 홈타이 방문 예약 안내',
    blurb:
      '처인구는 용인시청, 용인터미널, 명지대, 에버랜드를 중심으로 양지·백암·남사·이동 같은 넓은 차량 이동 생활권이 중요합니다. 도심 상권과 외곽 읍면 지역의 이동 기준이 크게 다르므로 예약 전 방문 가능 지역과 추가 이동비를 먼저 확인하는 것이 좋습니다.',
    areas: '용인시청, 용인중앙시장, 김량장, 명지대, 에버랜드, 양지·백암·남사·이동',
  },
  {
    slug: '/yongin/giheung-gu-chuljangmassage/',
    name: '기흥구',
    key: 'giheung',
    title: '기흥구 출장마사지｜기흥역·동백역·보정동 홈타이 안내',
    desc: '기흥구 출장마사지·홈타이 이용 전 기흥역, 동백역 주변 기준을 확인하세요.',
    h1: '기흥구 출장마사지 · 홈타이 방문 예약 안내',
    blurb:
      '기흥구는 기흥역, 동백역, 보정동, 신갈동, 구성동, 마북동처럼 역세권과 주거·업무 수요가 함께 있는 생활권입니다. 수인분당선과 용인경전철 에버라인이 지나고, 플랫폼시티 개발 이슈가 있는 구성·보정 생활권도 함께 참고하면 좋습니다.',
    areas: '기흥역, 동백역, 보정동, 신갈동, 구성동, 마북동',
  },
  {
    slug: '/yongin/suji-gu-chuljangmassage/',
    name: '수지구',
    key: 'suji',
    title: '수지구 출장마사지｜죽전역·수지구청역·성복역 안내',
    desc: '수지구 출장마사지·홈타이 예약 전 죽전역, 수지구청역 정보를 확인하세요.',
    h1: '수지구 출장마사지 · 홈타이 방문 예약 안내',
    blurb:
      '수지구는 죽전역, 수지구청역, 성복역, 상현역, 동천역을 중심으로 주거지와 강남 접근성이 강한 생활권입니다. 신분당선 역세권이 발달해 있어 죽전·풍덕천·성복·상현·동천 생활권별로 방문 기준을 나누어 확인하는 것이 좋습니다.',
    areas: '죽전역, 수지구청역, 성복역, 상현역, 동천역',
  },
];

const dongs = [
  // 처인구 (12)
  { slug: '/yongin/cheoin/pogok-eup-chuljangmassage/', name: '포곡읍', district: 'cheoin',
    title: '포곡읍 출장마사지｜에버랜드·전대리 생활권 안내',
    desc: '포곡읍 출장마사지·홈타이 예약 전 에버랜드, 전대리 생활권을 확인하세요.',
    blurb: '포곡읍은 에버랜드와 전대·에버랜드역, 둔전·보평 생활권을 중심으로 한 처인구 동부 지역입니다. 차량 이동 거리가 길 수 있어 예약 가능 시간과 추가 이동비를 먼저 확인하는 것이 좋습니다.' },
  { slug: '/yongin/cheoin/mohyeon-eup-chuljangmassage/', name: '모현읍', district: 'cheoin',
    title: '모현읍 출장마사지｜모현·외대 인근 홈타이 안내',
    desc: '모현읍 출장마사지·홈타이 예약 전 모현, 외대 인근 생활권을 확인하세요.',
    blurb: '모현읍은 외대·능원리 생활권을 중심으로 한 처인구 북부 지역입니다. 광주·분당 방면 접근성이 있는 차량 이동 생활권으로, 방문 가능 지역과 이동 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/cheoin/idong-eup-chuljangmassage/', name: '이동읍', district: 'cheoin',
    title: '이동읍 출장마사지｜이동읍 차량 방문 관리 안내',
    desc: '이동읍 출장마사지·홈타이 예약 전 이동읍 차량 방문 기준을 확인하세요.',
    blurb: '이동읍은 송전·덕성 생활권을 중심으로 한 처인구 남부의 차량 이동 지역입니다. 반도체 클러스터 교통 이슈로 통행량 변화가 있는 구간이므로 예약 가능 시간을 미리 확인하는 것이 좋습니다.' },
  { slug: '/yongin/cheoin/namsa-eup-chuljangmassage/', name: '남사읍', district: 'cheoin',
    title: '남사읍 출장마사지｜남사·반도체 생활권 안내',
    desc: '남사읍 출장마사지·홈타이 예약 전 남사, 반도체 생활권을 확인하세요.',
    blurb: '남사읍은 반도체 클러스터 조성으로 주목받는 처인구 남부 생활권입니다. 차량 이동 위주 지역으로 방문 가능 지역과 추가 이동비를 먼저 확인한 뒤 예약하는 것이 안전합니다.' },
  { slug: '/yongin/cheoin/yangji-eup-chuljangmassage/', name: '양지읍', district: 'cheoin',
    title: '양지읍 출장마사지｜양지IC·양지 생활권 홈타이 안내',
    desc: '양지읍 출장마사지·홈타이 예약 전 양지IC, 양지 생활권을 확인하세요.',
    blurb: '양지읍은 양지IC와 물류·주거 수요가 함께 있는 처인구 동부 생활권입니다. 영동고속도로 접근성이 좋아 차량 이동 기준을 중심으로 방문 가능 여부를 확인하면 좋습니다.' },
  { slug: '/yongin/cheoin/wonsam-myeon-chuljangmassage/', name: '원삼면', district: 'cheoin',
    title: '원삼면 출장마사지｜원삼면 외곽 방문 가능 지역 안내',
    desc: '원삼면 출장마사지·홈타이 예약 전 원삼면 외곽 방문 기준을 확인하세요.',
    blurb: '원삼면은 처인구 외곽의 차량 이동 생활권입니다. 이동 시간이 길어질 수 있으므로 예약 가능 시간, 추가 이동비, 방문 가능 지역을 먼저 확인하는 것이 좋습니다.' },
  { slug: '/yongin/cheoin/baegam-myeon-chuljangmassage/', name: '백암면', district: 'cheoin',
    title: '백암면 출장마사지｜백암면 차량 이동 홈타이 안내',
    desc: '백암면 출장마사지·홈타이 예약 전 백암면 차량 이동 기준을 확인하세요.',
    blurb: '백암면은 처인구 동남부 외곽의 차량 이동 생활권입니다. 도심에서 거리가 있는 편이라 예약 전 방문 가능 시간과 추가 이동비를 명확히 확인하는 것이 안전합니다.' },
  { slug: '/yongin/cheoin/jungang-dong-chuljangmassage/', name: '중앙동', district: 'cheoin',
    title: '중앙동 출장마사지｜용인중앙시장·김량장 생활권 안내',
    desc: '중앙동 출장마사지·홈타이 예약 전 용인중앙시장, 김량장을 확인하세요.',
    blurb: '중앙동은 용인중앙시장과 김량장역 생활권을 중심으로 한 처인구 도심 지역입니다. 상권이 밀집해 있어 방문 접근성이 좋은 편이며, 예약 절차와 이용 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/cheoin/yeokbuk-dong-chuljangmassage/', name: '역북동', district: 'cheoin',
    title: '역북동 출장마사지｜명지대·역북지구 홈타이 안내',
    desc: '역북동 출장마사지·홈타이 예약 전 명지대, 역북지구 생활권을 확인하세요.',
    blurb: '역북동은 명지대학교와 역북지구를 중심으로 한 처인구 도심 생활권입니다. 명지대역과 가까워 접근성이 좋은 편이며, 방문 가능 지역과 예약 기준을 확인하면 좋습니다.' },
  { slug: '/yongin/cheoin/samga-dong-chuljangmassage/', name: '삼가동', district: 'cheoin',
    title: '삼가동 출장마사지｜용인시청·삼가역 인근 안내',
    desc: '삼가동 출장마사지·홈타이 예약 전 용인시청, 삼가역 인근을 확인하세요.',
    blurb: '삼가동은 용인시청과 시청·용인대역, 삼가역을 중심으로 한 처인구 행정 생활권입니다. 경전철 접근성이 있어 방문 기준을 역세권과 함께 확인하면 좋습니다.' },
  { slug: '/yongin/cheoin/yurim-dong-chuljangmassage/', name: '유림동', district: 'cheoin',
    title: '유림동 출장마사지｜유림동 주거권 방문 관리 안내',
    desc: '유림동 출장마사지·홈타이 예약 전 유림동 주거권 방문 기준을 확인하세요.',
    blurb: '유림동은 유림1동·유림2동을 통합한 처인구 중심부 주거 생활권입니다. 차량 이동 기준을 중심으로 방문 가능 지역과 예약 시간을 확인하는 것이 좋습니다.' },
  { slug: '/yongin/cheoin/dongbu-dong-chuljangmassage/', name: '동부동', district: 'cheoin',
    title: '동부동 출장마사지｜마평·운학 생활권 홈타이 안내',
    desc: '동부동 출장마사지·홈타이 예약 전 마평, 운학 생활권을 확인하세요.',
    blurb: '동부동은 마평·운학 생활권을 포함한 처인구 중심부 지역입니다. 차량 이동 기준이 중요한 생활권으로 방문 가능 지역과 추가 이동비를 함께 확인하면 좋습니다.' },

  // 기흥구 (12)
  { slug: '/yongin/giheung/singal-dong-chuljangmassage/', name: '신갈동', district: 'giheung',
    title: '신갈동 출장마사지｜신갈역·기흥역 생활권 안내',
    desc: '신갈동 출장마사지·홈타이 예약 전 신갈역, 기흥역 생활권을 확인하세요.',
    blurb: '신갈동은 신갈역과 기흥역 주변 교통 접근성이 좋은 기흥구 중심 생활권입니다. 수인분당선 이용권으로 이동이 편리해 방문 예약 수요가 꾸준한 지역입니다.' },
  { slug: '/yongin/giheung/yeongdeok-dong-chuljangmassage/', name: '영덕동', district: 'giheung',
    title: '영덕동 출장마사지｜흥덕지구·광교 인접권 안내',
    desc: '영덕동 출장마사지·홈타이 예약 전 흥덕지구, 광교 인접권을 확인하세요.',
    blurb: '영덕동은 영덕1동·영덕2동을 통합한 흥덕지구 중심 생활권입니다. 광교·수원과 인접해 접근성이 좋은 편이며, 방문 가능 지역을 확인한 뒤 예약하면 좋습니다.' },
  { slug: '/yongin/giheung/gugal-dong-chuljangmassage/', name: '구갈동', district: 'giheung',
    title: '구갈동 출장마사지｜기흥역·구갈동 중심 안내',
    desc: '구갈동 출장마사지·홈타이 예약 전 기흥역, 구갈동 중심을 확인하세요.',
    blurb: '구갈동은 기흥역과 가까운 기흥구 중심 주거 생활권입니다. 수인분당선·에버라인 환승권과 인접해 이동이 편리한 지역으로 방문 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/giheung/sanggal-dong-chuljangmassage/', name: '상갈동', district: 'giheung',
    title: '상갈동 출장마사지｜상갈역·민속촌 생활권 안내',
    desc: '상갈동 출장마사지·홈타이 예약 전 상갈역, 민속촌 생활권을 확인하세요.',
    blurb: '상갈동은 상갈역, 한국민속촌, 기흥호수 인근을 포함한 기흥구 생활권입니다. 분당선 접근성이 있어 방문 기준을 역세권과 함께 확인하면 좋습니다.' },
  { slug: '/yongin/giheung/bora-dong-chuljangmassage/', name: '보라동', district: 'giheung',
    title: '보라동 출장마사지｜보라동·한국민속촌 인근 안내',
    desc: '보라동 출장마사지·홈타이 예약 전 보라동, 한국민속촌 인근을 확인하세요.',
    blurb: '보라동은 한국민속촌과 기흥호수 인근의 기흥구 주거 생활권입니다. 기흥역·상갈역 접근성이 있어 방문 가능 지역과 이동 기준을 확인하면 좋습니다.' },
  { slug: '/yongin/giheung/giheung-dong-chuljangmassage/', name: '기흥동', district: 'giheung',
    title: '기흥동 출장마사지｜기흥구 중심 생활권 안내',
    desc: '기흥동 출장마사지·홈타이 예약 전 기흥구 중심 생활권을 확인하세요.',
    blurb: '기흥동은 기흥구의 중심 생활권으로 주거와 상권이 함께 발달해 있습니다. 기흥역 접근성이 좋아 방문 예약 수요가 꾸준한 지역입니다.' },
  { slug: '/yongin/giheung/seonong-dong-chuljangmassage/', name: '서농동', district: 'giheung',
    title: '서농동 출장마사지｜서천·농서 생활권 홈타이 안내',
    desc: '서농동 출장마사지·홈타이 예약 전 서천, 농서 생활권을 확인하세요.',
    blurb: '서농동은 서천·농서 생활권을 포함한 기흥구 지역으로 흥덕·광교와 인접합니다. 차량 이동 접근성이 좋은 편이며 방문 가능 지역을 확인하면 좋습니다.' },
  { slug: '/yongin/giheung/guseong-dong-chuljangmassage/', name: '구성동', district: 'giheung',
    title: '구성동 출장마사지｜구성역·마북 인접권 안내',
    desc: '구성동 출장마사지·홈타이 예약 전 구성역, 마북 인접권을 확인하세요.',
    blurb: '구성동은 구성역과 마북동 인접권의 기흥구 생활권입니다. 용인 플랫폼시티 개발과 GTX-A 구성역 이슈가 있는 지역으로 향후 교통 변화도 함께 참고하면 좋습니다.' },
  { slug: '/yongin/giheung/mabuk-dong-chuljangmassage/', name: '마북동', district: 'giheung',
    title: '마북동 출장마사지｜마북동·보정 인근 홈타이 안내',
    desc: '마북동 출장마사지·홈타이 예약 전 마북동, 보정 인근을 확인하세요.',
    blurb: '마북동은 구성역과 보정동 인근의 기흥구 주거 생활권입니다. 플랫폼시티 개발권과 가까워 향후 생활권 변화도 함께 참고하면 좋습니다.' },
  { slug: '/yongin/giheung/dongbaek-dong-chuljangmassage/', name: '동백동', district: 'giheung',
    title: '동백동 출장마사지｜동백역·동백지구 안내',
    desc: '동백동 출장마사지·홈타이 이용 전 동백역, 초당역 주변 기준을 확인하세요.',
    blurb: '동백동은 동백1·2·3동을 통합한 동백역·어정역·초당역 생활권입니다. 동백지구 주거 밀집 지역으로 방문 예약 수요가 많아 예약 가능 시간을 미리 확인하면 좋습니다.' },
  { slug: '/yongin/giheung/sangha-dong-chuljangmassage/', name: '상하동', district: 'giheung',
    title: '상하동 출장마사지｜상하동 주거권 방문 관리 안내',
    desc: '상하동 출장마사지·홈타이 예약 전 상하동 주거권 방문 기준을 확인하세요.',
    blurb: '상하동은 동백지구와 인접한 기흥구 주거 생활권입니다. 동백역 접근성이 있어 방문 가능 지역과 이동 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/giheung/bojeong-dong-chuljangmassage/', name: '보정동', district: 'giheung',
    title: '보정동 출장마사지｜보정역·카페거리 생활권 안내',
    desc: '보정동 출장마사지·홈타이 예약 전 보정역, 카페거리 생활권을 확인하세요.',
    blurb: '보정동은 보정역과 죽전·보정 카페거리를 중심으로 한 기흥구 생활권입니다. 플랫폼시티 개발권과 인접해 향후 교통 변화도 함께 참고하면 좋습니다.' },

  // 수지구 (6)
  { slug: '/yongin/suji/pungdeokcheon-dong-chuljangmassage/', name: '풍덕천동', district: 'suji',
    title: '풍덕천동 출장마사지｜수지구청역 중심 생활권 안내',
    desc: '풍덕천동 출장마사지·홈타이 예약 전 수지구청역 중심 상권을 확인하세요.',
    blurb: '풍덕천동은 풍덕천1·2동을 통합한 수지구청역 중심 상권 생활권입니다. 수지 중심 상권이 밀집해 있어 방문 접근성이 좋은 편입니다.' },
  { slug: '/yongin/suji/sinbong-dong-chuljangmassage/', name: '신봉동', district: 'suji',
    title: '신봉동 출장마사지｜신봉동 주거권 홈타이 안내',
    desc: '신봉동 출장마사지·홈타이 예약 전 신봉동 주거권 방문 기준을 확인하세요.',
    blurb: '신봉동은 역세권보다 주거지와 차량 이동 기준이 중요한 수지구 생활권입니다. 광교산 인근 주거 밀집 지역으로 방문 가능 시간과 이동 기준을 확인하면 좋습니다.' },
  { slug: '/yongin/suji/jukjeon-dong-chuljangmassage/', name: '죽전동', district: 'suji',
    title: '죽전동 출장마사지｜죽전역·단국대 생활권 안내',
    desc: '죽전동 출장마사지·홈타이 예약 전 죽전역, 단국대 생활권을 확인하세요.',
    blurb: '죽전동은 죽전1·2·3동을 통합한 죽전역·단국대·보정동 카페거리 생활권입니다. 분당과 인접한 주거·상권 밀집 지역으로 방문 예약 수요가 꾸준합니다.' },
  { slug: '/yongin/suji/dongcheon-dong-chuljangmassage/', name: '동천동', district: 'suji',
    title: '동천동 출장마사지｜동천역·분당 인접권 안내',
    desc: '동천동 출장마사지·홈타이 예약 전 동천역, 분당 인접권을 확인하세요.',
    blurb: '동천동은 동천역과 판교·분당 접근성이 좋은 수지구 생활권입니다. 신분당선 이용권으로 강남 접근성이 강해 방문 예약 수요가 많은 지역입니다.' },
  { slug: '/yongin/suji/sanghyeon-dong-chuljangmassage/', name: '상현동', district: 'suji',
    title: '상현동 출장마사지｜상현역·광교 인접권 안내',
    desc: '상현동 출장마사지·홈타이 예약 전 상현역, 광교 인접권을 확인하세요.',
    blurb: '상현동은 상현1·2·3동을 통합한 상현역·광교 인접 생활권입니다. 신분당선 접근성이 좋아 방문 기준을 역세권과 함께 확인하면 좋습니다.' },
  { slug: '/yongin/suji/seongbok-dong-chuljangmassage/', name: '성복동', district: 'suji',
    title: '성복동 출장마사지｜성복역·성복동 주거권 안내',
    desc: '성복동 출장마사지·홈타이 예약 전 성복역, 롯데몰 생활권을 확인하세요.',
    blurb: '성복동은 성복역과 롯데몰을 중심으로 한 수지구 주거 생활권입니다. 신분당선 접근성과 대형 상권이 함께 있어 방문 예약 수요가 꾸준합니다.' },
];

const stations = [
  { slug: '/yongin/jukjeon-station-chuljangmassage/', name: '죽전역', district: 'suji',
    title: '죽전역 출장마사지｜죽전동·단국대 생활권 안내',
    desc: '죽전역 출장마사지·홈타이 예약 전 죽전동, 단국대 생활권을 확인하세요.',
    blurb: '죽전역은 죽전동, 단국대, 보정동 카페거리와 연결되는 수지구 역세권입니다. 분당과 인접한 생활권으로 방문 예약 수요가 꾸준합니다.' },
  { slug: '/yongin/bojeong-station-chuljangmassage/', name: '보정역', district: 'giheung',
    title: '보정역 출장마사지｜보정동·카페거리 홈타이 안내',
    desc: '보정역 출장마사지·홈타이 예약 전 보정동, 카페거리 생활권을 확인하세요.',
    blurb: '보정역은 보정동과 죽전·보정 카페거리를 중심으로 한 기흥구 역세권입니다. 플랫폼시티 개발권과 인접해 향후 변화도 함께 참고하면 좋습니다.' },
  { slug: '/yongin/guseong-station-chuljangmassage/', name: '구성역', district: 'giheung',
    title: '구성역 출장마사지｜구성동·마북동 생활권 안내',
    desc: '구성역 출장마사지·홈타이 예약 전 구성동, 마북동 생활권을 확인하세요.',
    blurb: '구성역은 구성동·마북동 생활권의 기흥구 역세권입니다. GTX-A 구성역과 용인 플랫폼시티 개발 이슈가 있어 향후 교통 변화도 함께 참고하면 좋습니다.' },
  { slug: '/yongin/singal-station-chuljangmassage/', name: '신갈역', district: 'giheung',
    title: '신갈역 출장마사지｜신갈동 중심 방문 관리 안내',
    desc: '신갈역 출장마사지·홈타이 예약 전 신갈동 중심 생활권을 확인하세요.',
    blurb: '신갈역은 신갈동을 중심으로 한 기흥구 역세권입니다. 수인분당선 이용권으로 이동이 편리해 방문 예약 수요가 꾸준한 지역입니다.' },
  { slug: '/yongin/giheung-station-chuljangmassage/', name: '기흥역', district: 'giheung',
    title: '기흥역 출장마사지｜수인분당선·에버라인 환승권 안내',
    desc: '기흥역 출장마사지·홈타이 예약 전 환승역 주변 방문 기준을 확인하세요.',
    blurb: '기흥역은 수인분당선과 용인경전철 에버라인이 만나는 환승 역세권입니다. 노선별로 페이지를 나누지 않고 기흥역 한 곳으로 안내하며, 신갈·구갈 생활권과 함께 방문 기준을 확인하면 좋습니다.' },
  { slug: '/yongin/sanggal-station-chuljangmassage/', name: '상갈역', district: 'giheung',
    title: '상갈역 출장마사지｜상갈동·민속촌 인근 안내',
    desc: '상갈역 출장마사지·홈타이 예약 전 상갈동, 민속촌 인근을 확인하세요.',
    blurb: '상갈역은 상갈동, 한국민속촌, 기흥호수 인근을 중심으로 한 기흥구 역세권입니다. 분당선 접근성이 있어 방문 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/dongcheon-station-chuljangmassage/', name: '동천역', district: 'suji',
    title: '동천역 출장마사지｜동천동·분당 인접 생활권 안내',
    desc: '동천역 출장마사지·홈타이 예약 전 동천동, 분당 인접권을 확인하세요.',
    blurb: '동천역은 동천동과 판교·분당 접근성이 좋은 수지구 신분당선 역세권입니다. 강남 접근성이 강해 방문 예약 수요가 많은 지역입니다.' },
  { slug: '/yongin/suji-gu-office-station-chuljangmassage/', name: '수지구청역', district: 'suji',
    title: '수지구청역 출장마사지｜풍덕천동 중심 상권 안내',
    desc: '수지구청역 출장마사지·홈타이 이용 전 풍덕천동 중심 상권을 확인하세요.',
    blurb: '수지구청역은 풍덕천동 중심 상권과 연결되는 수지구 신분당선 역세권입니다. 수지 중심 상권이 밀집해 있어 방문 접근성이 좋은 편입니다.' },
  { slug: '/yongin/seongbok-station-chuljangmassage/', name: '성복역', district: 'suji',
    title: '성복역 출장마사지｜성복동·롯데몰 생활권 안내',
    desc: '성복역 출장마사지·홈타이 예약 전 성복동, 롯데몰 생활권을 확인하세요.',
    blurb: '성복역은 성복동과 롯데몰을 중심으로 한 수지구 신분당선 역세권입니다. 대형 상권과 주거지가 함께 있어 방문 예약 수요가 꾸준합니다.' },
  { slug: '/yongin/sanghyeon-station-chuljangmassage/', name: '상현역', district: 'suji',
    title: '상현역 출장마사지｜상현동·광교 인접권 안내',
    desc: '상현역 출장마사지·홈타이 예약 전 상현동, 광교 인접권을 확인하세요.',
    blurb: '상현역은 상현동과 광교 인접권을 중심으로 한 수지구 신분당선 역세권입니다. 광교 접근성이 좋아 방문 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/gangnamdae-station-chuljangmassage/', name: '강남대역', district: 'giheung',
    title: '강남대역 출장마사지｜강남대·기흥구 생활권 안내',
    desc: '강남대역 출장마사지·홈타이 이용 전 강남대, 기흥구 생활권을 확인하세요.',
    blurb: '강남대역은 강남대학교와 기흥구 생활권을 연결하는 용인경전철 에버라인 역세권입니다. 방문 가능 지역과 이동 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/jiseok-station-chuljangmassage/', name: '지석역', district: 'giheung',
    title: '지석역 출장마사지｜동백·지석 생활권 안내',
    desc: '지석역 출장마사지·홈타이 예약 전 동백, 지석 생활권을 확인하세요.',
    blurb: '지석역은 동백지구와 지석 생활권을 연결하는 용인경전철 에버라인 역세권입니다. 동백동 주거권과 함께 방문 기준을 확인하면 좋습니다.' },
  { slug: '/yongin/eojeong-station-chuljangmassage/', name: '어정역', district: 'giheung',
    title: '어정역 출장마사지｜동백지구 어정 생활권 안내',
    desc: '어정역 출장마사지·홈타이 이용 전 동백지구 어정 생활권을 확인하세요.',
    blurb: '어정역은 동백지구 어정 생활권을 연결하는 용인경전철 에버라인 역세권입니다. 동백동 주거 밀집권과 가까워 방문 예약 수요가 있는 지역입니다.' },
  { slug: '/yongin/dongbaek-station-chuljangmassage/', name: '동백역', district: 'giheung',
    title: '동백역 출장마사지｜동백지구 홈타이 예약 안내',
    desc: '동백역 출장마사지·홈타이 예약 전 동백지구 방문 기준을 확인하세요.',
    blurb: '동백역은 동백지구를 중심으로 한 용인경전철 에버라인 역세권입니다. 동백1·2·3동 주거 밀집 지역과 연결되어 방문 예약 수요가 많은 곳입니다.' },
  { slug: '/yongin/chodang-station-chuljangmassage/', name: '초당역', district: 'giheung',
    title: '초당역 출장마사지｜동백·초당지구 생활권 안내',
    desc: '초당역 출장마사지·홈타이 이용 전 동백, 초당지구 생활권을 확인하세요.',
    blurb: '초당역은 동백지구 초당 생활권을 연결하는 용인경전철 에버라인 역세권입니다. 동백동 주거권과 함께 방문 가능 지역을 확인하면 좋습니다.' },
  { slug: '/yongin/samga-station-chuljangmassage/', name: '삼가역', district: 'cheoin',
    title: '삼가역 출장마사지｜용인시청·삼가동 생활권 안내',
    desc: '삼가역 출장마사지·홈타이 예약 전 용인시청, 삼가동 생활권을 확인하세요.',
    blurb: '삼가역은 용인시청과 삼가동을 연결하는 용인경전철 에버라인 역세권입니다. 처인구 행정 생활권과 가까워 방문 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/yongin-cityhall-yongin-univ-station-chuljangmassage/', name: '시청·용인대역', district: 'cheoin',
    title: '시청·용인대역 출장마사지｜용인시청·삼가동 안내',
    desc: '시청·용인대역 출장마사지·홈타이 예약 전 용인시청, 삼가동을 확인하세요.',
    blurb: '시청·용인대역은 용인시청과 용인대학교, 삼가동을 연결하는 용인경전철 에버라인 역세권입니다. 처인구 중심 생활권으로 방문 예약 수요가 있는 지역입니다.' },
  { slug: '/yongin/myeongji-univ-station-chuljangmassage/', name: '명지대역', district: 'cheoin',
    title: '명지대역 출장마사지｜역북동·명지대 생활권 안내',
    desc: '명지대역 출장마사지·홈타이 예약 전 역북동, 명지대 생활권을 확인하세요.',
    blurb: '명지대역은 명지대학교와 역북지구를 연결하는 용인경전철 에버라인 역세권입니다. 처인구 도심 생활권으로 접근성이 좋은 편입니다.' },
  { slug: '/yongin/gimnyangjang-station-chuljangmassage/', name: '김량장역', district: 'cheoin',
    title: '김량장역 출장마사지｜중앙동·용인시장 안내',
    desc: '김량장역 출장마사지·홈타이 예약 전 중앙동, 용인시장 생활권을 확인하세요.',
    blurb: '김량장역은 중앙동과 용인중앙시장을 연결하는 용인경전철 에버라인 역세권입니다. 처인구 도심 상권이 밀집해 방문 접근성이 좋은 편입니다.' },
  { slug: '/yongin/stadium-songdam-univ-station-chuljangmassage/', name: '운동장·송담대역', district: 'cheoin',
    title: '운동장·송담대역 출장마사지｜처인구 운동장 생활권 안내',
    desc: '운동장·송담대역 출장마사지·홈타이 이용 전 처인구 생활권을 확인하세요.',
    blurb: '운동장·송담대역은 용인종합운동장과 송담대학교를 연결하는 용인경전철 에버라인 역세권입니다. 처인구 도심 생활권으로 방문 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/gojin-station-chuljangmassage/', name: '고진역', district: 'cheoin',
    title: '고진역 출장마사지｜용인경전철 고진 생활권 안내',
    desc: '고진역 출장마사지·홈타이 예약 전 고진 생활권 방문 기준을 확인하세요.',
    blurb: '고진역은 용인경전철 에버라인이 지나는 처인구 동부 역세권입니다. 포곡·둔전 방면 생활권과 연결되어 방문 가능 지역을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/bopyeong-station-chuljangmassage/', name: '보평역', district: 'cheoin',
    title: '보평역 출장마사지｜포곡·보평 생활권 안내',
    desc: '보평역 출장마사지·홈타이 이용 전 포곡, 보평 생활권을 확인하세요.',
    blurb: '보평역은 포곡읍 보평 생활권을 연결하는 용인경전철 에버라인 역세권입니다. 에버랜드 방면 생활권과 가까워 방문 기준을 함께 확인하면 좋습니다.' },
  { slug: '/yongin/dunjeon-station-chuljangmassage/', name: '둔전역', district: 'cheoin',
    title: '둔전역 출장마사지｜포곡읍·둔전 생활권 안내',
    desc: '둔전역 출장마사지·홈타이 예약 전 포곡읍, 둔전 생활권을 확인하세요.',
    blurb: '둔전역은 포곡읍 둔전 생활권을 연결하는 용인경전철 에버라인 역세권입니다. 에버랜드 방면과 가까운 차량 이동 생활권으로 방문 기준을 확인하면 좋습니다.' },
  { slug: '/yongin/jeondae-everland-station-chuljangmassage/', name: '전대·에버랜드역', district: 'cheoin',
    title: '전대·에버랜드역 출장마사지｜포곡읍·에버랜드 생활권 안내',
    desc: '전대·에버랜드역 출장마사지·홈타이 예약 전 포곡읍 생활권을 확인하세요.',
    blurb: '전대·에버랜드역은 포곡읍과 에버랜드를 연결하는 용인경전철 에버라인 종점 역세권입니다. 차량 이동 거리가 있는 생활권이므로 예약 가능 시간을 미리 확인하면 좋습니다.' },
];

const pages = [
  { slug: '/reservation/', name: '예약 안내', menu: '예약 안내',
    title: '예약 안내｜간다GO 용인 출장마사지·홈타이',
    desc: '용인 출장마사지·홈타이 예약 방법과 전화 예약 절차를 안내합니다.' },
  { slug: '/notice/', name: '이용 전 확인사항', menu: '이용 전 확인사항',
    title: '이용 전 확인사항｜간다GO 용인 출장마사지',
    desc: '용인 출장마사지·홈타이 이용 전 방문 지역, 시간, 결제 기준을 확인하세요.' },
  { slug: '/homethai-guide/', name: '홈타이 이용 가이드', menu: '홈타이 이용 가이드',
    title: '홈타이 이용 가이드｜간다GO 용인 출장마사지',
    desc: '용인 홈타이 이용 가이드와 방문형 관리 서비스 절차를 안내합니다.' },
  { slug: '/privacy/', name: '개인정보 처리방침', menu: '개인정보 처리방침',
    title: '개인정보 처리방침｜간다GO 용인 출장마사지',
    desc: '간다GO 용인 출장마사지 사이트의 개인정보 처리방침 안내입니다.' },
  { slug: '/support/', name: '고객센터', menu: '고객센터',
    title: '고객센터｜간다GO 용인 출장마사지·홈타이',
    desc: '간다GO 용인 출장마사지·홈타이 고객센터 전화 예약 및 문의 안내입니다.' },
];

module.exports = { districts, dongs, stations, pages };
